apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: urcheckin
  namespace: urcheckin
  labels:
    app: urcheckin
spec:
  serviceName: urcheckin
  replicas: 4
  selector:
    matchLabels:
      app: urcheckin
  template:
    metadata:
      labels:
        app: urcheckin
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'urcheckin-dev'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-inject-secret-env-config: 'kv/urcheckin-dev'
        vault.hashicorp.com/agent-inject-template-env-config: |
            {{ with secret "kv/urcheckin-dev" -}}
              {{- range $key, $value := .Data.data }}
                export {{ $key }}="{{ $value }}"
              {{- end }}
            {{- end }}
    spec:
      serviceAccountName: urcheckin-dev-auth
      containers:
        - name: urcheckin
          image: ideavn/urcheckin:{latest}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 50m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: urcheckin-service
  namespace: urcheckin
spec:
  selector:
    app: urcheckin
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: urcheckin-ingress
  namespace: urcheckin
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  rules:
  - host: urcheckin.urtest.click
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: urcheckin-service
            port:
              number: 3000
